version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: tradingbotv2-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tradingbotv2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tradingbotv2"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: